variable subscription_id {}
variable tenant_id {}
variable client_id {}
variable client_secret {}
variable rm_env {}
variable resource_env {}
variable location {}
variable resource_group_name {}
variable virtual_network_cidr {}
variable public_subnet_cidr {}
variable general_public_instances {}
variable key_data {}
